# Configuration: https://herb-tools.dev/configuration

version: 0.9.7

files:
  exclude:
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

linter:
  enabled: true

  rules:
    erb-no-unsafe-raw:
      enabled: false
    erb-no-instance-variables-in-partials:
      enabled: false
    erb-no-trailing-whitespace:
      enabled: false
    erb-no-duplicate-branch-elements:
      enabled: false
    html-no-unescaped-entities:
      enabled: false # Stimulus data-action uses > in attribute values
    html-anchor-require-href:
      enabled: false
    html-require-script-nonce:
      enabled: false

formatter:
  enabled: true
  indentWidth: 2
  maxLineLength: 80
